// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrwcjcpmbxfscdefzumr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyd2NqY3BtYnhmc2NkZWZ6dW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjg3NzksImV4cCI6MjA2NTgwNDc3OX0.zWypZXT8k7qVx25zHtHNq1NBhf9ztpU2vFBDmhWH6sA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);